#!/usr/bin/env python3
"""Score AI analytics readiness from taxonomy inputs and issue logs."""
from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise SystemExit(f"Input file not found: {path}")
    with path.open(newline="", encoding="utf-8") as f:
        return [{k: (v or "").strip() for k, v in row.items()} for row in csv.DictReader(f)]


def clamp(value: int) -> int:
    return max(0, min(100, value))


def score(events: list[dict[str, str]], properties: list[dict[str, str]], issues: list[dict[str, str]]) -> dict:
    counts = Counter(i.get("issue_type", "unknown") for i in issues)
    severity = Counter(i.get("severity", "unknown") for i in issues)
    total_events = max(1, len(events))
    total_properties = max(1, len(properties))

    event_desc_ratio = sum(1 for e in events if e.get("description")) / total_events
    event_owner_ratio = sum(1 for e in events if e.get("owner")) / total_events
    property_desc_ratio = sum(1 for p in properties if p.get("description")) / total_properties

    coverage = clamp(round(100 * ((event_desc_ratio + property_desc_ratio) / 2) - severity["high"] * 4))
    clarity = clamp(100 - counts["generic_property_name"] * 8 - counts["duplicate_like_event_names"] * 10 - counts["missing_event_description"] * 5)
    consistency = clamp(100 - counts["inconsistent_property_type"] * 20 - counts["duplicate_like_event_names"] * 12)
    governance = clamp(round(100 * event_owner_ratio) - counts["missing_property_owner"] * 4 - counts["deprecated_event_still_active"] * 15)
    overall = round((coverage + clarity + consistency + governance) / 4)

    level = "ready"
    if overall < 50:
        level = "not_ready"
    elif overall < 75:
        level = "needs_cleanup"

    return {
        "overall_score": overall,
        "readiness_level": level,
        "dimensions": {
            "coverage": coverage,
            "clarity": clarity,
            "consistency": consistency,
            "governance": governance,
        },
        "issue_counts": dict(counts),
        "severity_counts": dict(severity),
        "inputs": {"events": len(events), "properties": len(properties), "issues": len(issues)},
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Score taxonomy readiness for AI analytics.")
    parser.add_argument("--events", required=True, help="Path to event inventory CSV")
    parser.add_argument("--properties", required=True, help="Path to property dictionary CSV")
    parser.add_argument("--issues", required=True, help="Path to issue CSV generated by validate_taxonomy.py")
    parser.add_argument("--out", default="outputs/readiness_score.json", help="Output JSON path")
    args = parser.parse_args()

    result = score(read_csv(Path(args.events)), read_csv(Path(args.properties)), read_csv(Path(args.issues)))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote readiness score {result['overall_score']} ({result['readiness_level']}) to {out}")


if __name__ == "__main__":
    main()
